import Link from "next/link";
import { Toaster } from "react-hot-toast";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="font-normal">
        <div className="flex flex-row">
          <div>
           <Link href="/">HOME | </Link>
          <Link href="/pages/Clientes">CLIENTES | </Link>
          <Link href="/pages/Eventos">EVENTOS | </Link>
          <Link href="/pages/Ingressos">INGRESSOS</Link>
          </div >
          <Toaster/>
          
        </div>
        <div className="flex flex-row">            
          {children}
          </div>       
        </body>
    </html>
  );
}
